[project]
name = "repl-nix-datavisualizermessenger-1"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "pandas>=2.2.3",
    "sqlalchemy>=2.0.36",
    "sqlite3database>=0.2.0",
    "werkzeug>=3.1.3",
]
